services:
  spidey:
    build: .
    container_name: spidey
    ports:
      - "${PORT:-8000}:8000"
    # Pass runtime secrets/config (Bearer, HF token, etc.)
    env_file:
      - .env
    environment:
      - HF_HOME=/cache/hf
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    volumes:
      - ./models:/app/models
      - ./store:/app/store
      - hf-cache:/cache/hf
    restart: unless-stopped
    # GPU (optional) — uncomment if NVIDIA runtime is set up:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf-cache: {}

